language: php

sudo: false

php:
- 7.1.3
- 7.2.0
- 7.3.0

install:
- echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
- composer install --prefer-dist

cache:
  directories:
    - $HOME/.composer/cache

script:
  - vendor/bin/phpcs --ignore=/vendor/,/app/ --standard=vendor/magento/magento-coding-standard/Magento2/ --extensions=php ./

after_script:
- php vendor/bin/coveralls
